#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

const EXPECTED_DESI_TRACERS = ['BGS', 'ELG', 'LRG', 'QSO'];
const NON_HUMAN_AUTHORSHIP_PATTERNS = [
  /\[bot\]/i,
  /\bbot\b/i,
  /automated assistant/i,
  /language model/i,
  /co-authored-by/i,
  /generated by/i,
];

const failures = [];
const warnings = [];
const checks = [];

function resolveRepo(...parts) {
  return path.join(ROOT, ...parts);
}

function relativePath(filePath) {
  return path.relative(ROOT, filePath).replaceAll(path.sep, '/');
}

function readJson(relative) {
  const filePath = resolveRepo(relative);
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    failures.push(`Unable to parse ${relative}: ${error.message}`);
    return null;
  }
}

function sha256File(filePath) {
  const hash = crypto.createHash('sha256');
  hash.update(fs.readFileSync(filePath));
  return hash.digest('hex');
}

function stableJson(value) {
  if (Array.isArray(value)) {
    return `[${value.map(stableJson).join(',')}]`;
  }
  if (value && typeof value === 'object') {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

function addCheck(name, passed, detail) {
  checks.push({ name, passed, detail });
  if (!passed) failures.push(`${name}: ${detail}`);
}

function addWarning(detail) {
  warnings.push(detail);
}

function fileStats(relative) {
  const filePath = resolveRepo(relative);
  if (!fs.existsSync(filePath)) {
    addCheck(`file exists: ${relative}`, false, 'missing');
    return null;
  }
  const stats = fs.statSync(filePath);
  return {
    path: relative,
    bytes: stats.size,
    sha256: sha256File(filePath),
  };
}

function formatInteger(value) {
  return Number(value).toLocaleString('en-US');
}

function formatBytes(bytes) {
  if (!Number.isFinite(bytes)) return 'n/a';
  const units = ['B', 'KiB', 'MiB', 'GiB'];
  let value = bytes;
  let unitIndex = 0;
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024;
    unitIndex += 1;
  }
  return `${value.toFixed(unitIndex === 0 ? 0 : 2)} ${units[unitIndex]}`;
}

function finiteNumber(value) {
  return typeof value === 'number' && Number.isFinite(value);
}

function tracerFromObjectId(value) {
  if (typeof value !== 'string') return null;
  const match = /^desi-dr1:([^:]+):/.exec(value);
  return match ? match[1] : null;
}

function sumObjectValues(record) {
  return Object.values(record).reduce((sum, value) => sum + Number(value || 0), 0);
}

function validateHumanAuthorshipMetadata(label, value) {
  const text = stableJson(value);
  const matched = NON_HUMAN_AUTHORSHIP_PATTERNS.find((pattern) => pattern.test(text));
  addCheck(`${label} contains no non-human authorship metadata`, !matched, matched ? `matched ${matched}` : 'clean');
}

function validateRegistry(registry) {
  if (!registry) return null;
  addCheck('survey registry format', registry.format === 'nasadiya-survey-registry/v4', registry.format || 'missing format');
  addCheck('survey registry layer array', Array.isArray(registry.layers) && registry.layers.length >= 5, `${registry.layers?.length || 0} layers`);
  validateHumanAuthorshipMetadata('survey registry', registry);

  const layers = new Map((registry.layers || []).map((layer) => [layer.id, layer]));
  const requiredLayers = ['2mrs-table3', 'desi-dr1-lss'];
  for (const id of requiredLayers) {
    const layer = layers.get(id);
    addCheck(`registry deployed layer ${id}`, Boolean(layer && layer.readiness === 'deployed'), layer ? layer.readiness : 'missing');
  }

  for (const layer of registry.layers || []) {
    const isFuture = ['planned', 'blocked'].includes(layer.readiness);
    if (layer.measurement_kind?.includes('photometric') && isFuture) {
      addCheck(
        `photometric uncertainty gate ${layer.id}`,
        Array.isArray(layer.required_contract) && layer.required_contract.some((field) => field.includes('uncertainty')),
        JSON.stringify(layer.required_contract || []),
      );
    }
  }
  return layers;
}

function validate2mrs(manifest, catalogue) {
  if (!manifest || !catalogue) return null;

  const browserPath = 'data/processed/2mrs/2mrs_lightcone.json';
  const browserFile = fileStats(browserPath);
  addCheck('2MRS manifest synthetic flag', manifest.is_synthetic === false, `is_synthetic=${manifest.is_synthetic}`);
  addCheck('2MRS browser checksum', browserFile?.sha256 === manifest.browser_catalog_sha256, browserFile?.sha256 || 'missing file');
  addCheck('2MRS browser object array', Array.isArray(catalogue.objects), `${catalogue.objects?.length || 0} rows`);
  addCheck('2MRS object count matches manifest', catalogue.objects?.length === manifest.object_count, `${catalogue.objects?.length || 0} vs ${manifest.object_count}`);
  addCheck('2MRS metadata count matches objects', catalogue.meta?.object_count === catalogue.objects?.length, `${catalogue.meta?.object_count} vs ${catalogue.objects?.length || 0}`);
  addCheck('2MRS metadata source table', catalogue.meta?.source_table === 'J/ApJS/199/26/table3', catalogue.meta?.source_table || 'missing');
  addCheck('2MRS metadata synthetic flag', catalogue.meta?.is_synthetic === false, `is_synthetic=${catalogue.meta?.is_synthetic}`);
  validateHumanAuthorshipMetadata('2MRS catalogue', catalogue.meta || {});

  const seen = new Set();
  const badRows = [];
  let minCz = Infinity;
  let maxCz = -Infinity;
  for (const [index, row] of (catalogue.objects || []).entries()) {
    if (typeof row.object_id !== 'string' || seen.has(row.object_id)) badRows.push(`row ${index} duplicate/missing object_id`);
    seen.add(row.object_id);
    if (row.is_synthetic !== false) badRows.push(`row ${index} synthetic flag is not false`);
    if (!finiteNumber(row.ra_deg) || row.ra_deg < 0 || row.ra_deg >= 360) badRows.push(`row ${index} invalid RA`);
    if (!finiteNumber(row.dec_deg) || row.dec_deg < -90 || row.dec_deg > 90) badRows.push(`row ${index} invalid Dec`);
    if (!finiteNumber(row.cz_km_s)) badRows.push(`row ${index} invalid cz`);
    if (finiteNumber(row.cz_km_s)) {
      minCz = Math.min(minCz, row.cz_km_s);
      maxCz = Math.max(maxCz, row.cz_km_s);
    }
    if (badRows.length > 10) break;
  }
  addCheck('2MRS row-level observed-coordinate contract', badRows.length === 0, badRows.length ? badRows.join('; ') : `${formatInteger(seen.size)} unique observed rows`);

  return {
    dataset_id: manifest.dataset_id,
    object_count: manifest.object_count,
    file: browserFile,
    cz_km_s_range: [minCz, maxCz],
  };
}

function validateDesiIndex(index) {
  if (!index) return null;
  addCheck('DESI index format', index.format === 'nasadiya-tile-store/v1', index.format || 'missing format');
  addCheck('DESI dataset synthetic flag', index.dataset?.is_synthetic === false, `is_synthetic=${index.dataset?.is_synthetic}`);
  addCheck('DESI index tile count', index.tile_count === index.tiles?.length, `${index.tile_count} vs ${index.tiles?.length || 0}`);
  addCheck('DESI overview count declared', Number.isInteger(index.overview?.count) && index.overview.count > 0, `${index.overview?.count || 0}`);
  validateHumanAuthorshipMetadata('DESI index dataset metadata', index.dataset || {});

  const tileSum = (index.tiles || []).reduce((sum, tile) => sum + Number(tile.count || 0), 0);
  addCheck('DESI tile counts sum to record_count', tileSum === index.record_count, `${formatInteger(tileSum)} vs ${formatInteger(index.record_count)}`);

  let missingTiles = 0;
  let invalidBounds = 0;
  let nonPositiveTiles = 0;
  for (const tile of index.tiles || []) {
    const tilePath = resolveRepo('data/processed/desi-dr1', tile.path || '');
    if (!fs.existsSync(tilePath)) missingTiles += 1;
    if (!Number.isInteger(tile.count) || tile.count <= 0) nonPositiveTiles += 1;
    const bounds = tile.bounds || {};
    for (const key of ['x_mpc', 'y_mpc', 'z_mpc', 'redshift']) {
      const pair = bounds[key];
      if (!Array.isArray(pair) || pair.length !== 2 || !finiteNumber(pair[0]) || !finiteNumber(pair[1]) || pair[0] > pair[1]) {
        invalidBounds += 1;
      }
    }
  }
  addCheck('DESI tile files are present', missingTiles === 0, `${missingTiles} missing of ${index.tiles?.length || 0}`);
  addCheck('DESI tile counts are positive', nonPositiveTiles === 0, `${nonPositiveTiles} non-positive tiles`);
  addCheck('DESI tile bounds are finite', invalidBounds === 0, `${invalidBounds} invalid bound arrays`);

  const sourceMap = index.source_mapping || {};
  const sourceFiles = Array.isArray(sourceMap.files) ? sourceMap.files : [];
  const sourceAcceptedRows = sourceFiles.reduce((sum, file) => sum + Number(file.accepted_rows || 0), 0);
  addCheck('DESI source mapping file ledger', sourceFiles.length >= EXPECTED_DESI_TRACERS.length * 2, `${sourceFiles.length} files`);
  addCheck('DESI source mapping row conservation', sourceAcceptedRows === index.record_count, `${formatInteger(sourceAcceptedRows)} vs ${formatInteger(index.record_count)}`);
  addCheck('DESI source mapping marks overview as LOD', sourceMap.overview_is_not_a_scientific_selection === true, String(sourceMap.overview_is_not_a_scientific_selection));
  for (const tracer of EXPECTED_DESI_TRACERS) {
    const filesForTracer = sourceFiles.filter((file) => String(file.component || '').toUpperCase() === tracer);
    const rowsForTracer = filesForTracer.reduce((sum, file) => sum + Number(file.accepted_rows || 0), 0);
    const checksumFailures = filesForTracer.filter((file) => !/^[a-f0-9]{64}$/i.test(file.sha256 || '')).length;
    addCheck(`DESI source files include ${tracer}`, filesForTracer.length > 0 && rowsForTracer > 0, `${filesForTracer.length} files, ${formatInteger(rowsForTracer)} rows`);
    addCheck(`DESI source file checksums ${tracer}`, checksumFailures === 0, `${checksumFailures} malformed checksums`);
  }

  return {
    dataset_id: index.dataset?.dataset_id,
    record_count: index.record_count,
    tile_count: index.tile_count,
    tile_count_sum: tileSum,
    overview_count: index.overview?.count,
    source_url: index.dataset?.source_url,
  };
}

function validateDesiOverview(index, overview) {
  if (!index || !overview) return null;
  addCheck('DESI overview format', overview.format === index.format, `${overview.format} vs ${index.format}`);
  addCheck('DESI overview dataset id', overview.dataset_id === index.dataset?.dataset_id, `${overview.dataset_id} vs ${index.dataset?.dataset_id}`);
  addCheck('DESI overview columns match index', JSON.stringify(overview.columns) === JSON.stringify(index.record_columns), 'column contract comparison');
  addCheck('DESI overview row count', overview.records?.length === index.overview?.count, `${overview.records?.length || 0} vs ${index.overview?.count}`);
  addCheck('DESI overview declares non-scientific LOD', overview.selection?.not_a_scientific_selection === true, JSON.stringify(overview.selection || {}));

  const columnIndex = new Map((overview.columns || []).map((column, indexPosition) => [column, indexPosition]));
  const requiredColumns = ['object_id', 'ra_deg', 'dec_deg', 'redshift', 'comoving_distance_mpc', 'lookback_time_gyr', 'x_mpc', 'y_mpc', 'z_mpc'];
  for (const column of requiredColumns) {
    addCheck(`DESI overview has ${column}`, columnIndex.has(column), columnIndex.has(column) ? 'present' : 'missing');
  }

  const seen = new Set();
  const tracerCounts = Object.fromEntries(EXPECTED_DESI_TRACERS.map((tracer) => [tracer, 0]));
  const badRows = [];
  let minZ = Infinity;
  let maxZ = -Infinity;
  let minDistance = Infinity;
  let maxDistance = -Infinity;
  for (const [rowIndex, record] of (overview.records || []).entries()) {
    const objectId = record[columnIndex.get('object_id')];
    const tracer = tracerFromObjectId(objectId);
    if (!tracerCounts.hasOwnProperty(tracer)) badRows.push(`row ${rowIndex} invalid tracer/object_id`);
    else tracerCounts[tracer] += 1;
    if (seen.has(objectId)) badRows.push(`row ${rowIndex} duplicate object_id`);
    seen.add(objectId);

    const ra = record[columnIndex.get('ra_deg')];
    const dec = record[columnIndex.get('dec_deg')];
    const redshift = record[columnIndex.get('redshift')];
    const distance = record[columnIndex.get('comoving_distance_mpc')];
    const lookback = record[columnIndex.get('lookback_time_gyr')];
    if (!finiteNumber(ra) || ra < 0 || ra >= 360) badRows.push(`row ${rowIndex} invalid RA`);
    if (!finiteNumber(dec) || dec < -90 || dec > 90) badRows.push(`row ${rowIndex} invalid Dec`);
    if (!finiteNumber(redshift) || redshift < 0 || redshift > 5) badRows.push(`row ${rowIndex} invalid redshift`);
    if (!finiteNumber(distance) || distance < 0) badRows.push(`row ${rowIndex} invalid comoving distance`);
    if (!finiteNumber(lookback) || lookback < 0) badRows.push(`row ${rowIndex} invalid lookback time`);
    for (const axis of ['x_mpc', 'y_mpc', 'z_mpc']) {
      const value = record[columnIndex.get(axis)];
      if (!finiteNumber(value)) badRows.push(`row ${rowIndex} invalid ${axis}`);
    }
    if (finiteNumber(redshift)) {
      minZ = Math.min(minZ, redshift);
      maxZ = Math.max(maxZ, redshift);
    }
    if (finiteNumber(distance)) {
      minDistance = Math.min(minDistance, distance);
      maxDistance = Math.max(maxDistance, distance);
    }
    if (badRows.length > 10) break;
  }
  addCheck('DESI overview row-level coordinate contract', badRows.length === 0, badRows.length ? badRows.join('; ') : `${formatInteger(seen.size)} unique observed rows`);

  return {
    file: fileStats('data/processed/desi-dr1/overview.json'),
    record_count: overview.records?.length || 0,
    tracer_counts: tracerCounts,
    redshift_range: [minZ, maxZ],
    comoving_distance_mpc_range: [minDistance, maxDistance],
  };
}

function validateFullCloud(index, fullCloud) {
  if (!index || !fullCloud) return null;
  addCheck('full-cloud format', fullCloud.format === 'nasadiya-gpu-cloud/v1', fullCloud.format || 'missing format');
  addCheck('full-cloud row count matches DESI index', fullCloud.record_count === index.record_count, `${formatInteger(fullCloud.record_count)} vs ${formatInteger(index.record_count)}`);
  addCheck('full-cloud rejected rows', fullCloud.rejected_rows === 0, `${fullCloud.rejected_rows}`);
  addCheck('full-cloud observed source kind', fullCloud.source?.measurement_kind === 'spectroscopic', fullCloud.source?.measurement_kind || 'missing');

  const expectedBytes = fullCloud.record_count * fullCloud.binary?.stride_bytes;
  addCheck('full-cloud byte length matches stride contract', expectedBytes === fullCloud.binary?.byte_length, `${formatInteger(expectedBytes)} vs ${formatInteger(fullCloud.binary?.byte_length)}`);
  addCheck('full-cloud field order', JSON.stringify(fullCloud.binary?.fields) === JSON.stringify(['x_mpc', 'y_mpc', 'z_mpc', 'redshift', 'tracer_code']), JSON.stringify(fullCloud.binary?.fields || []));

  const partReports = [];
  let summedBytes = 0;
  for (const part of fullCloud.binary?.parts || []) {
    const relative = `data/processed/desi-dr1/full-cloud/${part.path}`;
    const info = fileStats(relative);
    if (!info) continue;
    summedBytes += info.bytes;
    addCheck(`full-cloud part size ${part.path}`, info.bytes === part.byte_length, `${formatBytes(info.bytes)} vs ${formatBytes(part.byte_length)}`);
    addCheck(`full-cloud part checksum ${part.path}`, info.sha256 === part.sha256, info.sha256);
    partReports.push({
      path: relative,
      bytes: info.bytes,
      sha256: info.sha256,
    });
  }
  addCheck('full-cloud summed byte length', summedBytes === fullCloud.binary?.byte_length, `${formatBytes(summedBytes)} vs ${formatBytes(fullCloud.binary?.byte_length)}`);

  const tracerTotal = sumObjectValues(fullCloud.tracer_counts || {});
  addCheck('full-cloud tracer counts sum to record count', tracerTotal === fullCloud.record_count, `${formatInteger(tracerTotal)} vs ${formatInteger(fullCloud.record_count)}`);
  for (const tracer of EXPECTED_DESI_TRACERS) {
    addCheck(`full-cloud tracer count ${tracer}`, Number.isInteger(fullCloud.tracer_counts?.[tracer]) && fullCloud.tracer_counts[tracer] > 0, `${fullCloud.tracer_counts?.[tracer] || 0}`);
  }
  validateHumanAuthorshipMetadata('full-cloud metadata', {
    source: fullCloud.source,
    rendering_scope: fullCloud.rendering_scope,
    delivery: fullCloud.delivery,
  });

  return {
    dataset_id: fullCloud.dataset_id,
    record_count: fullCloud.record_count,
    byte_length: fullCloud.binary?.byte_length,
    part_count: fullCloud.binary?.parts?.length || 0,
    parts: partReports,
    tracer_counts: fullCloud.tracer_counts,
  };
}

function validateResearchSummary(index, fullCloud, summary) {
  if (!index || !summary) return null;
  addCheck('research summary parent rows match DESI index', summary.input_rows === index.record_count, `${formatInteger(summary.input_rows)} vs ${formatInteger(index.record_count)}`);
  addCheck('research summary rendered rows contract', summary.rendered_rows === summary.requested_render_rows, `${formatInteger(summary.rendered_rows)} vs ${formatInteger(summary.requested_render_rows)}`);
  addCheck('research summary marked observed', summary.is_synthetic === false, `is_synthetic=${summary.is_synthetic}`);

  const tracerTotal = sumObjectValues(summary.tracer_counts || {});
  addCheck('research summary tracer counts sum to input rows', tracerTotal === summary.input_rows, `${formatInteger(tracerTotal)} vs ${formatInteger(summary.input_rows)}`);
  if (fullCloud) {
    addCheck('research summary tracer counts match full-cloud', JSON.stringify(summary.tracer_counts) === JSON.stringify(fullCloud.tracer_counts), 'tracer count comparison');
  }

  for (const tracer of EXPECTED_DESI_TRACERS) {
    const histogramSum = (summary.redshift_histogram?.counts?.[tracer] || []).reduce((sum, value) => sum + Number(value || 0), 0);
    addCheck(`research redshift histogram sum ${tracer}`, histogramSum === summary.tracer_counts?.[tracer], `${formatInteger(histogramSum)} vs ${formatInteger(summary.tracer_counts?.[tracer])}`);
  }
  addCheck('research summary sky footprint boundary', summary.sky_footprint?.not_physical_density === true, JSON.stringify(summary.sky_footprint || {}));

  const figureFiles = [
    'figures/desi_dr1_lss_3d_research_view.png',
    'figures/desi_dr1_lss_redshift_summary.png',
    'figures/desi_dr1_lss_sky_footprint.png',
    'figures/desi_dr1_lss_research_summary.json',
  ];
  const figureReports = [];
  for (const figure of figureFiles) {
    const info = fileStats(figure);
    if (info) {
      addCheck(`research figure non-empty ${figure}`, info.bytes > 1024, `${formatBytes(info.bytes)}`);
      figureReports.push(info);
    }
  }

  return {
    input_rows: summary.input_rows,
    rendered_rows: summary.rendered_rows,
    tracer_counts: summary.tracer_counts,
    maximum_observed_redshift: summary.redshift_histogram?.maximum_observed_redshift,
    maximum_comoving_distance_mpc: summary.maximum_comoving_distance_mpc,
    maximum_lookback_time_gyr: summary.maximum_lookback_time_gyr,
    figure_files: figureReports,
  };
}

function validatePublicationEvidence(index, evidence) {
  if (!index || !evidence) return null;
  addCheck('publication evidence format', evidence.format === 'nasadiya-publication-evidence/v1', evidence.format || 'missing format');
  addCheck('publication evidence parent rows', evidence.input?.validated_parent_rows === index.record_count, `${formatInteger(evidence.input?.validated_parent_rows)} vs ${formatInteger(index.record_count)}`);
  addCheck('publication evidence GPU manifest match', evidence.gpu_render_contract?.parent_rows_match_manifest === true, JSON.stringify(evidence.gpu_render_contract || {}));
  addCheck('publication evidence observed-row boundary', evidence.scientific_boundary?.observed_rows_only === true, JSON.stringify(evidence.scientific_boundary || {}));
  addCheck('publication evidence no density reconstruction claim', evidence.scientific_boundary?.density_reconstruction === false, JSON.stringify(evidence.scientific_boundary || {}));
  validateHumanAuthorshipMetadata('publication evidence metadata', evidence);

  const csvPath = 'figures/publication_evidence/representation_fidelity_metrics.csv';
  const csvStats = fileStats(csvPath);
  let csvRows = 0;
  if (csvStats) {
    const lines = fs.readFileSync(resolveRepo(csvPath), 'utf8').trim().split(/\r?\n/);
    csvRows = Math.max(0, lines.length - 1);
    addCheck('publication fidelity CSV has measurements', csvRows > 0, `${csvRows} rows`);
  }

  const expectedFigureCount = evidence.figure_files?.length || 0;
  if (expectedFigureCount === 0) {
    addWarning('Publication evidence manifest lists no figure identifiers.');
  }

  return {
    parent_rows: evidence.input?.validated_parent_rows,
    input_sha256: evidence.input?.sha256,
    gpu_manifest_record_count: evidence.gpu_render_contract?.manifest_record_count,
    fidelity_csv: csvStats,
    fidelity_rows: csvRows,
    figure_identifiers: evidence.figure_files || [],
  };
}

function buildReport(payload) {
  const passCount = checks.filter((check) => check.passed).length;
  const failCount = checks.length - passCount;
  const lines = [];
  lines.push('# NASADIYA Survey Integrity Ledger');
  lines.push('');
  lines.push('This report is generated by `node scripts/audit_survey_integrity.mjs`. It verifies that the committed browser and research evidence products remain tied to observed survey rows, with synthetic layers and unstated density reconstructions kept out of the catalogue path.');
  lines.push('');
  lines.push(`- Status: **${payload.status.toUpperCase()}**`);
  lines.push(`- Integrity fingerprint: \`${payload.integrity_fingerprint}\``);
  lines.push(`- Checks passed: ${passCount}/${checks.length}`);
  lines.push(`- Warnings: ${warnings.length}`);
  lines.push('');
  lines.push('## Survey Products');
  lines.push('');
  lines.push('| Product | Rows | Files | Notes |');
  lines.push('|---|---:|---:|---|');
  lines.push(`| 2MRS Table 3 browser catalogue | ${formatInteger(payload.products.two_mrs.object_count)} | 1 JSON | Hash-verified observed spectroscopic anchor; cz range ${payload.products.two_mrs.cz_km_s_range.map((value) => formatInteger(value)).join(' to ')} km/s. |`);
  lines.push(`| DESI DR1 LSS tile index | ${formatInteger(payload.products.desi_index.record_count)} | ${formatInteger(payload.products.desi_index.tile_count)} tiles | Tile counts sum exactly to the index record count. |`);
  lines.push(`| DESI browser overview | ${formatInteger(payload.products.desi_overview.record_count)} | 1 JSON | Deterministic level-of-detail from real source rows; not a scientific subsample. |`);
  lines.push(`| DESI full GPU cloud | ${formatInteger(payload.products.full_cloud.record_count)} | ${payload.products.full_cloud.part_count} binary chunks | ${formatBytes(payload.products.full_cloud.byte_length)} shader-ready float32 observed-row cloud. |`);
  lines.push('');
  lines.push('## DESI Tracer Counts');
  lines.push('');
  lines.push('| Tracer | Full catalogue rows | Browser overview rows |');
  lines.push('|---|---:|---:|');
  for (const tracer of EXPECTED_DESI_TRACERS) {
    lines.push(`| ${tracer} | ${formatInteger(payload.products.full_cloud.tracer_counts[tracer])} | ${formatInteger(payload.products.desi_overview.tracer_counts[tracer])} |`);
  }
  lines.push('');
  lines.push('## Research Evidence');
  lines.push('');
  lines.push(`The research-summary figures scan ${formatInteger(payload.products.research_summary.input_rows)} DESI rows and render ${formatInteger(payload.products.research_summary.rendered_rows)} deterministic rows for the 3D figure. Maximum observed redshift is ${payload.products.research_summary.maximum_observed_redshift.toFixed(4)}, maximum comoving distance is ${payload.products.research_summary.maximum_comoving_distance_mpc.toFixed(2)} Mpc, and maximum lookback time is ${payload.products.research_summary.maximum_lookback_time_gyr.toFixed(2)} Gyr.`);
  lines.push('');
  lines.push('| Evidence file | Size | SHA-256 |');
  lines.push('|---|---:|---|');
  for (const file of payload.products.research_summary.figure_files) {
    lines.push(`| \`${file.path}\` | ${formatBytes(file.bytes)} | \`${file.sha256}\` |`);
  }
  if (payload.products.publication_evidence.fidelity_csv) {
    const file = payload.products.publication_evidence.fidelity_csv;
    lines.push(`| \`${file.path}\` | ${formatBytes(file.bytes)} | \`${file.sha256}\` |`);
  }
  lines.push('');
  lines.push('## Scientific Boundaries');
  lines.push('');
  lines.push('- Catalogue objects must carry survey provenance and may not be generated decorative points.');
  lines.push('- The public DESI overview is a deterministic browser level-of-detail layer, not a statistically complete scientific subsample.');
  lines.push('- Publication evidence validates representation fidelity of observed rows; it does not claim a clustering estimator, random catalogue, completeness correction, or density reconstruction.');
  lines.push('- Planned photometric-redshift and mission products remain gated on per-object uncertainty and release provenance.');
  lines.push('');
  lines.push('## Machine Checks');
  lines.push('');
  lines.push('| Check | Result | Detail |');
  lines.push('|---|---|---|');
  for (const check of checks) {
    lines.push(`| ${check.name.replaceAll('|', '\\|')} | ${check.passed ? 'PASS' : 'FAIL'} | ${String(check.detail).replaceAll('|', '\\|')} |`);
  }
  if (warnings.length) {
    lines.push('');
    lines.push('## Warnings');
    lines.push('');
    for (const warning of warnings) lines.push(`- ${warning}`);
  }
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function writeIfChanged(relative, content) {
  const filePath = resolveRepo(relative);
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  if (fs.existsSync(filePath)) {
    const previous = fs.readFileSync(filePath, 'utf8');
    if (previous === content) return false;
  }
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

const registry = readJson('data/registry/surveys.json');
const twoMrsManifest = readJson('data/processed/2mrs/manifest.json');
const twoMrsCatalogue = readJson('data/processed/2mrs/2mrs_lightcone.json');
const desiIndex = readJson('data/processed/desi-dr1/index.json');
const desiOverview = readJson('data/processed/desi-dr1/overview.json');
const fullCloud = readJson('data/processed/desi-dr1/full-cloud/full-cloud.json');
const researchSummary = readJson('figures/desi_dr1_lss_research_summary.json');
const publicationEvidence = readJson('figures/publication_evidence/evidence_manifest.json');

validateRegistry(registry);
const products = {
  two_mrs: validate2mrs(twoMrsManifest, twoMrsCatalogue),
  desi_index: validateDesiIndex(desiIndex),
  desi_overview: validateDesiOverview(desiIndex, desiOverview),
  full_cloud: validateFullCloud(desiIndex, fullCloud),
  research_summary: validateResearchSummary(desiIndex, fullCloud, researchSummary),
  publication_evidence: validatePublicationEvidence(desiIndex, publicationEvidence),
};

if (Object.values(products).some((value) => value === null)) {
  failures.push('One or more product audits could not be completed.');
}

const fingerprintSource = {
  checks: checks.map((check) => [check.name, check.passed, check.detail]),
  products,
  warnings,
};
const integrityFingerprint = crypto.createHash('sha256').update(stableJson(fingerprintSource)).digest('hex');
const payload = {
  format: 'nasadiya-survey-integrity/v1',
  status: failures.length ? 'failed' : 'passed',
  integrity_fingerprint: integrityFingerprint,
  products,
  checks,
  warnings,
};

writeIfChanged('data/registry/survey_integrity.json', `${JSON.stringify(payload, null, 2)}\n`);
writeIfChanged('SURVEY_INTEGRITY.md', buildReport(payload));

const passed = checks.filter((check) => check.passed).length;
const failed = checks.length - passed;
console.log(`Survey integrity audit: ${passed}/${checks.length} checks passed, ${failed} failed, ${warnings.length} warnings.`);
console.log(`Integrity fingerprint: ${integrityFingerprint}`);
console.log(`Wrote ${relativePath(resolveRepo('data/registry/survey_integrity.json'))} and ${relativePath(resolveRepo('SURVEY_INTEGRITY.md'))}.`);

if (failures.length) {
  console.error('\nFailures:');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}
